name: places_surf
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  auto_route: ^10.1.0+1
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  drift_flutter: ^0.2.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.2.0
  geolocator: ^14.0.2
  get_it: ^8.0.3
  path_provider: ^2.1.5
  retrofit: ^4.6.0
  rxdart: ^0.28.0
  yandex_maps_mapkit: ^4.18.0-beta

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.1.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  retrofit_generator: ^9.7.0
  drift_dev: ^2.28.0

flutter:
  uses-material-design: true

  assets:
    - .env